name: First Test
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Bye Bye"
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.1.0
